from datetime import datetime
from time import strftime

f1=datetime.now()
f2=strftime("%Y-%m-%d %I:%M:%S")
f3=strftime("%m/%d/%Y")
f4=strftime("%A,%B %d, %Y")
f5=strftime("%A,%B %d, %Y %H:%M:%S %p")
f6=strftime("%A-%b-%d %H:%M:%S %Z %Y")
f7=strftime("%a-%b-%d %H:%M:%S %Z %Y")
f8 = f1.isoformat(sep='T', timespec="auto")
f9=strftime("%d")
f10=strftime("%H:%M:%S")
f11=strftime("%B")
f12=strftime("%Y")
print(f1)
print(f2)
print(f3)
print(f4)
print(f5)
print(f6)
print(f7)
print(f8)
print(f9)
print(f10)
print(f11)
print(f12)